Add PHP 8.3
laminas/laminas-xmlrpc pull request #37
Opened 2023-11-21 15:00 UTC by SuperDJ

2023-11-21 15:08 UTC, Ocramius requested changes

2023-11-21 15:08 UTC, Ocramius commented on composer.json
> +        "php": "~8.1.0 || ~8.2.0 || ~8.3.0",
`composer.lock` needs updating (try with `composer update nothing`)

2023-11-22 15:33 UTC, SuperDJ commented
This PR requires https://github.com/laminas/laminas-xml/pull/17

2023-11-24 17:51 UTC, Ocramius commented
@SuperDJ if you give this a rebase on top of `2.19.x`, we should be green, and this could probably be merged + released :)

2023-11-27 22:26 UTC, Xerkus commented
Superseded by #39

2023-11-27 22:26 UTC, closed without merging